# k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urlshortener-api
  template:
    metadata:
      labels:
        app: urlshortener-api
    spec:
      containers:
      - name: urlshortener-api
        image: ammar11233/urlshortener:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis-service:6379"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017"


---

apiVersion: v1
kind: Service
metadata:
  name: urlshortener-api
spec:
  selector:
    app: urlshortener-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
